# Generated by Django 3.0 on 2021-03-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosVacunacion',
            fields=[
                ('sender', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('delegacion', models.TextField(blank=True, null=True)),
                ('pertenece_medico', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'registros_vacunacion',
                'managed': False,
            },
        ),
    ]
